# Instalando biblioteca readxl para importar para o R arquivos com extensão .xls ou .xlsx.
if (!("readxl") %in% installed.packages()) install.packages("readxl")
library(readxl)
covid_19_bauru_mortes <- read_excel("dados/covid_19_bauru_mortes.xlsx")
privado <- length(covid_19_bauru_mortes$tipo_hosp[which(covid_19_bauru_mortes$tipo_hosp=="privado")])
publico <- length(covid_19_bauru_mortes$tipo_hosp[which(covid_19_bauru_mortes$tipo_hosp=="público")])
unique(privado)
unique(publico)
dados <- table(covid_19_bauru_mortes$tipo_hosp)
barplot(dados, main="Mortes Tipos de Hospitais", xlab = "Tipos de hospitais", ylab = "Total", col="blue")
covid_19_bauru_mortes$inicio_sintoma <- as.Date(covid_19_bauru_mortes$inicio_sintoma)
covid_19_bauru_mortes$data_obito <- as.Date(covid_19_bauru_mortes$data_obito)
covid_19_bauru_mortes[["permanencia"]] <- difftime(covid_19_bauru_mortes$data_obito, covid_19_bauru_mortes$inicio_sintoma, units = "days")
permanencia_privado <- mean(covid_19_bauru_mortes$permanencia[which(covid_19_bauru_mortes$tipo_hosp=="privado")])
permanencia_publico <- mean(covid_19_bauru_mortes$permanencia[which(covid_19_bauru_mortes$tipo_hosp=="público")])
